### ISSUE TITLE
AttributeError: module 'torch.jit' has no attribute 'unused' error

### ISSUE THREAD

**Issue by siddharthdivi** [jdavid04/lapool#1]
Hello, 

I get the following error **"AttributeError: module 'torch.jit' has no attribute 'unused' error"** , when I run any one of the sample commands given under the **"Running Experiments"** section. 

I did install all the packages mentioned in the **"env.yml"** file, but even after that I still encounter this issue. 

There is a similar issue reported here : [(https://github.com/pytorch/pytorch/issues/26608)] , wherein they mention installing **'nightly'** as a potential solution, which I did do but the error still exists. 

Do you have any idea of how to get this working ?

**Comment by jdhorwood** [comment]
Hi,

This seems like a torch version issue. Can you try upgrading to pytorch 1.4.0?

**Comment by siddharthdivi** [comment]
Is your yml file correct? I can see that you've updated the Torch version. I did try upgrading to Torch 1.4. If you could upload the correct yml file, then I can just create an environment directly from that. That would be helpful. Thanks!

**Comment by jdhorwood** [comment]
Hi, 

The yml file is platform-dependent, so we've added a stripped-down linux version along with one generated on osx. Hopefully this should allow you to run without issue.

**Comment by siddharthdivi** [comment]
It works now, thank you!
